name: "Pull Latest Pages"

on:
  schedule:
    - cron: '0 20 * * *'
  push:
    branches: [ main ]
    workflow_dispatch:

jobs:
  analyze:
    name: Pull Latest Pages
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python3' ]
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Install Aria2
      run: sudo apt update && sudo apt install -y aria2

    - name: Install Pillow
      run: pip install Pillow

    - name: Download Checkpoint
      run: true || aria2c -d . https://github.com/trunghieumickey/priconne-manga-compiler/releases/download/latest/URI-LIST.txt https://github.com/trunghieumickey/priconne-manga-compiler/releases/download/latest/LOST-PAGE.txt
      
    - name: Pull Pages
      run: python3 priconne-pull.py
    
    - name: Update Release
      uses: pyTooling/Actions/releaser@main
      with:
        tag: latest
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          priconne.pdf
          URI-LIST.txt
          LOST-PAGE.txt

