name: "Pull Latest Pages"

on:
  schedule:
    - cron: '0 20 * * *'
  push:
    branches: [ main ]
    workflow_dispatch:

jobs:
  analyze:
    name: Pull Latest Pages
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python3' ]
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Install Dependencies
      run: sudo apt update && sudo apt full-upgrade -y && sudo apt install -y aria2 libwebp-dev zip

    - name: Install Pillow
      run: pip install Pillow

    - name: Download Url List
      run: aria2c -d . https://github.com/trunghieumickey/priconne-manga-compiler/releases/download/latest/URI-LIST.txt || true

    - name: Download Checkpoint
      run: aria2c -d . https://github.com/trunghieumickey/priconne-manga-compiler/releases/download/latest/LOST-PAGE.txt || true

    - name: Download Cover Page
      run: aria2c -d . https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/6db99da0e4835f3b334a2704b704d0ef.jpe -o cover.jpg || true

    - name: Pull Pages
      run: python3 priconne-pull.py

    - name: Make Tachiyomi Release
      run: python3 priconne-tachiyomi.py
    
    - name: Update Release
      uses: pyTooling/Actions/releaser@main
      with:
        tag: latest
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          priconne.pdf
          priconne.zip
          URI-LIST.txt
          LOST-PAGE.txt

